apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "ontaix.labels" . | nindent 4 }}
  {{- if .Values.workloadIdentity.clientId }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
  {{- end }}
automountServiceAccountToken: false
