"""End-to-end bootstrap: create the super admin in the stack's database, as the admin CLI does.

Reads `{"email": ..., "password": ...}` from stdin (the password is generated by the test run
and exists only in memory), connects with ONTAIX_DATABASE_URL on the login's own privileges,
and prints nothing about the password. Run with apps/api as the working directory and its
virtual environment's interpreter.
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd()))

from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine  # noqa: E402

from app.clients.db_client import async_database_url  # noqa: E402
from app.config import get_settings  # noqa: E402

# `account` has a foreign key to `tenant`; its mapping must be registered before the first
# flush, and nothing on this path imports it otherwise.
from app.models.storage import tenant as _tenant_mapping  # noqa: E402, F401
from app.services import super_admin_service  # noqa: E402


async def main() -> None:
    request = json.loads(sys.stdin.read())
    url = get_settings().database_url
    if not url:
        raise SystemExit("ONTAIX_DATABASE_URL is not set")
    engine = create_async_engine(async_database_url(url), hide_parameters=True)
    try:
        async with async_sessionmaker(engine, expire_on_commit=False)() as session:
            await super_admin_service.create_super_admin(
                session, request["email"], request["password"]
            )
            await session.commit()
    finally:
        await engine.dispose()


if __name__ == "__main__":
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    asyncio.run(main())
    print("super admin created")
