-- Ontaix control plane · PostgreSQL 16 schema.
-- System of record for the ontology, proposals, identity, bindings, audit and the outbox.
-- Every row belongs to one tenant: every table carries tenant_id, every parent exposes
-- UNIQUE (tenant_id, id), and every child foreign key is composite on (tenant_id, <parent>_id),
-- so a row can never reference another tenant's row. Identifiers are UUIDs generated by the database.
-- Domain product versions are integer revisions rendered as v1.<revision>.
-- Grants: the application role holds INSERT and SELECT only on audit_entry; nobody holds
-- UPDATE, DELETE or TRUNCATE on it, and the triggers below refuse them for every role.

BEGIN;

CREATE SCHEMA IF NOT EXISTS ontaix;
SET search_path TO ontaix, public;

-- ---------------------------------------------------------------------------
-- Enumerations
-- ---------------------------------------------------------------------------

CREATE TYPE node_kind AS ENUM ('root', 'concept');
CREATE TYPE relation_kind AS ENUM ('rel', 'isa', 'same', 'clash');
CREATE TYPE proposal_type AS ENUM ('concept', 'spec', 'relation', 'source', 'bind', 'attr', 'change');
CREATE TYPE proposal_state AS ENUM ('pending', 'half_approved', 'approved', 'rejected');
CREATE TYPE proposal_origin AS ENUM ('text', 'speech', 'document');
CREATE TYPE change_kind AS ENUM (
  'rename', 'delete_concept', 'edit_relation', 'remove_relation', 'unbind',
  'rename_source', 'remove_source', 'remove_company', 'resolve_conflict', 'remove_cross_company_links'
);
CREATE TYPE attribute_type AS ENUM ('id', 'text', 'number', 'ref', 'date');
CREATE TYPE attribute_state AS ENUM ('proposed', 'approved');
CREATE TYPE role_name AS ENUM ('owner', 'builder', 'governor', 'member', 'administrator', 'auditor', 'agent');
CREATE TYPE scope_kind AS ENUM ('tenant', 'company', 'domain');
CREATE TYPE actor_kind AS ENUM ('user', 'agent', 'system');
CREATE TYPE source_auth AS ENUM ('service_principal', 'oauth2_client_credentials', 'managed_identity', 'key_vault_api_key');
CREATE TYPE refresh_interval AS ENUM ('5 min', '15 min', '1 h', 'daily');
CREATE TYPE theme_name AS ENUM ('dark', 'light');
CREATE TYPE binding_freshness AS ENUM ('2 min', '4 min', '11 min', '1 h', 'paused', 'just now');

-- ---------------------------------------------------------------------------
-- Tenant, identity providers, settings, view state
-- ---------------------------------------------------------------------------

CREATE TABLE tenant (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        text NOT NULL UNIQUE,
  name        text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE tenant IS 'One customer of the control plane; every other row points at exactly one tenant.';

CREATE TABLE tenant_identity_provider (
  tenant_id   uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  issuer      text NOT NULL,
  audience    text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, issuer, audience),
  UNIQUE (issuer, audience)
);
COMMENT ON TABLE tenant_identity_provider IS 'Which OIDC issuer and audience pairs sign users and agents into which tenant; the pair is unique across tenants so a token maps to exactly one tenant.';

CREATE TABLE tenant_settings (
  tenant_id            uuid PRIMARY KEY REFERENCES tenant(id) ON DELETE CASCADE,
  theme                theme_name NOT NULL DEFAULT 'dark',
  colors               jsonb NOT NULL DEFAULT '{}'::jsonb,
  accent               text NOT NULL DEFAULT '#3fb8a9',
  source_colour        text NOT NULL DEFAULT '#d6bd8a',
  voice                boolean NOT NULL DEFAULT true,
  import_docs          boolean NOT NULL DEFAULT true,
  live_teaching        boolean NOT NULL DEFAULT true,
  everyone_teaches     boolean NOT NULL DEFAULT false,
  approval_required    boolean NOT NULL DEFAULT true CHECK (approval_required),
  two_approvers        boolean NOT NULL DEFAULT false,
  auto_attrs           boolean NOT NULL DEFAULT false,
  notify_owners        boolean NOT NULL DEFAULT true,
  multi_company        boolean NOT NULL DEFAULT true,
  cross_company        boolean NOT NULL DEFAULT true,
  animations           boolean NOT NULL DEFAULT true,
  coverage_default     boolean NOT NULL DEFAULT false,
  legend               boolean NOT NULL DEFAULT true,
  read_only_connectors boolean NOT NULL DEFAULT true CHECK (read_only_connectors),
  refresh              refresh_interval NOT NULL DEFAULT '15 min',
  agent_access         boolean NOT NULL DEFAULT true,
  cost_cap             boolean NOT NULL DEFAULT true,
  llm_monthly_token_cap bigint NOT NULL DEFAULT 2000000 CHECK (llm_monthly_token_cap BETWEEN 0 AND 1000000000),
  egress_allowlist     text[] NOT NULL DEFAULT '{}',
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tenant_settings_colors_is_object CHECK (jsonb_typeof(colors) = 'object')
);
COMMENT ON TABLE tenant_settings IS 'The 22 tenant settings plus appearance, the connector egress allowlist and the monthly token cap of Ontaix''s own language model calls (0 turns the teach extraction model step off); the two locked settings are enforced by CHECK constraints.';

CREATE TABLE tenant_view_state (
  tenant_id   uuid PRIMARY KEY REFERENCES tenant(id) ON DELETE CASCADE,
  coverage    boolean NOT NULL DEFAULT false,
  updated_at  timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE tenant_view_state IS 'Shared canvas state that survives reload: the coverage flag.';

-- ---------------------------------------------------------------------------
-- Ontology: companies, domain products, concepts, relations
-- ---------------------------------------------------------------------------

CREATE TABLE company (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  key         text NOT NULL,
  name        text NOT NULL,
  sub         text NOT NULL DEFAULT '',
  position    integer NOT NULL,
  is_home     boolean NOT NULL DEFAULT false,
  dying_at    timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, key),
  UNIQUE (tenant_id, position)
);
CREATE UNIQUE INDEX company_one_home_per_tenant ON company (tenant_id) WHERE is_home;
COMMENT ON TABLE company IS 'A business-as-a-product in the tenant; the home company (position 0) cannot be removed.';

CREATE TABLE domain_template (
  key         text PRIMARY KEY,
  name        text NOT NULL,
  owner       text NOT NULL,
  color       text NOT NULL,
  position    integer NOT NULL UNIQUE
);
COMMENT ON TABLE domain_template IS 'The nine fixed domain product templates every company is instantiated from, in ring order.';

CREATE TABLE domain_product (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  company_id    uuid NOT NULL,
  template_key  text NOT NULL REFERENCES domain_template(key),
  revision      integer NOT NULL DEFAULT 0 CHECK (revision >= 0),
  hidden        boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (company_id, template_key),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE
);
COMMENT ON TABLE domain_product IS 'One owned, versioned slice per company and template; revision increments by one on every approved change that carries the domain.';

CREATE TABLE concept (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id          uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  company_id         uuid NOT NULL,
  kind               node_kind NOT NULL DEFAULT 'concept',
  label              text NOT NULL,
  sub                text NOT NULL DEFAULT '',
  domain_product_id  uuid,
  rule               text,
  pending            boolean NOT NULL DEFAULT true,
  conflict           boolean NOT NULL DEFAULT false,
  parent_id          uuid,
  birth_relation_id  uuid,
  birth_action       text,
  birth_reverse      boolean NOT NULL DEFAULT false,
  born_at            timestamptz NOT NULL DEFAULT now(),
  x                  double precision NOT NULL DEFAULT 0,
  y                  double precision NOT NULL DEFAULT 0,
  pinned             boolean NOT NULL DEFAULT false,
  dying_at           timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, domain_product_id) REFERENCES domain_product(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, parent_id) REFERENCES concept(tenant_id, id) ON DELETE SET NULL (parent_id),
  CONSTRAINT concept_root_has_no_domain CHECK (kind <> 'root' OR domain_product_id IS NULL),
  CONSTRAINT concept_root_has_no_parent CHECK (kind <> 'root' OR parent_id IS NULL),
  CONSTRAINT concept_non_root_has_domain CHECK (kind = 'root' OR domain_product_id IS NOT NULL),
  CONSTRAINT concept_non_root_has_birth_action CHECK (kind = 'root' OR birth_action IS NOT NULL),
  CONSTRAINT concept_label_not_blank CHECK (length(btrim(label)) > 0)
);
CREATE UNIQUE INDEX concept_one_root_per_company ON concept (company_id) WHERE kind = 'root';
CREATE UNIQUE INDEX concept_label_unique_per_company ON concept (company_id, lower(label)) WHERE dying_at IS NULL;
CREATE INDEX concept_by_domain ON concept (domain_product_id);
CREATE INDEX concept_by_parent ON concept (parent_id);
COMMENT ON TABLE concept IS 'A cell on the canvas: the company root or a concept born by division, with its lineage (parent, birth link, birth action and direction, born_at) and stored position.';

CREATE TABLE relation (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  a_id        uuid NOT NULL,
  b_id        uuid NOT NULL,
  kind        relation_kind NOT NULL,
  label       text NOT NULL,
  rest        numeric(6,1) NOT NULL,
  seed        double precision NOT NULL,
  pending     boolean NOT NULL DEFAULT true,
  dying_at    timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, a_id) REFERENCES concept(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, b_id) REFERENCES concept(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT relation_ends_differ CHECK (a_id <> b_id),
  CONSTRAINT relation_seed_unit CHECK (seed >= 0 AND seed < 1),
  CONSTRAINT relation_structural_label CHECK (
    (kind = 'isa' AND label = 'is a') OR
    (kind = 'same' AND label = 'equivalent to') OR
    (kind = 'clash' AND label = 'conflicts with') OR
    (kind = 'rel')
  )
);
CREATE UNIQUE INDEX relation_unique_triple ON relation (a_id, lower(label), b_id) WHERE dying_at IS NULL;
CREATE INDEX relation_by_a ON relation (a_id);
CREATE INDEX relation_by_b ON relation (b_id);
COMMENT ON TABLE relation IS 'A directed line between two concepts: action relation, specialisation (is a), cross-company equivalence or a noticed conflict.';

ALTER TABLE concept
  ADD CONSTRAINT concept_birth_relation_fk FOREIGN KEY (tenant_id, birth_relation_id)
  REFERENCES relation(tenant_id, id) ON DELETE SET NULL (birth_relation_id) DEFERRABLE INITIALLY DEFERRED;

-- ---------------------------------------------------------------------------
-- Bindings: connectors, sources, bindings, attributes
-- ---------------------------------------------------------------------------

CREATE TABLE connector_type (
  code        text PRIMARY KEY,
  name        text NOT NULL,
  category    text NOT NULL,
  scope_text  text NOT NULL,
  position    integer NOT NULL UNIQUE
);
COMMENT ON TABLE connector_type IS 'The read-only connector catalogue shown on the Connectors page and in wizard step 1.';

CREATE TABLE source (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  company_id      uuid NOT NULL,
  label           text NOT NULL,
  kind_text       text NOT NULL,
  connector_code  text REFERENCES connector_type(code),
  host            text,
  scope           text,
  auth            source_auth,
  credential_ref  text CHECK (credential_ref ~ '^[A-Za-z0-9-]{1,127}$'),
  refresh         refresh_interval NOT NULL DEFAULT '15 min',
  anchor_index    integer NOT NULL CHECK (anchor_index >= 0),
  disabled        boolean NOT NULL DEFAULT false,
  pending         boolean NOT NULL DEFAULT true,
  x               double precision NOT NULL DEFAULT 0,
  y               double precision NOT NULL DEFAULT 0,
  pinned          boolean NOT NULL DEFAULT false,
  dying_at        timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX source_label_unique_per_company ON source (company_id, lower(label)) WHERE dying_at IS NULL;
COMMENT ON TABLE source IS 'A connected system drawn as a brass square outside the domain ring; credential_ref is a Key Vault secret name, never a credential value.';

CREATE TABLE binding (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  source_id   uuid NOT NULL,
  concept_id  uuid NOT NULL,
  records     bigint NOT NULL DEFAULT 0 CHECK (records >= 0),
  fresh       binding_freshness NOT NULL DEFAULT '2 min',
  seed        double precision CHECK (seed >= 0 AND seed < 1),
  pending     boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (concept_id),
  FOREIGN KEY (tenant_id, source_id) REFERENCES source(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, concept_id) REFERENCES concept(tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX binding_by_source ON binding (source_id);
COMMENT ON TABLE binding IS 'The bind link from a source to a concept with record count and freshness; a concept has at most one binding.';

CREATE TABLE attribute (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  concept_id  uuid NOT NULL,
  source_id   uuid,
  name        text NOT NULL,
  type        attribute_type NOT NULL,
  col         text NOT NULL,
  fill        smallint NOT NULL CHECK (fill BETWEEN 0 AND 100),
  state       attribute_state NOT NULL DEFAULT 'proposed',
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (concept_id, name),
  FOREIGN KEY (tenant_id, concept_id) REFERENCES concept(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, source_id) REFERENCES source(tenant_id, id) ON DELETE SET NULL (source_id)
);
COMMENT ON TABLE attribute IS 'An attribute read from a bound source: name, type, source column, fill percentage and whether it is approved or still proposed.';

-- ---------------------------------------------------------------------------
-- Identity: users, groups, roles, agents, cost
-- ---------------------------------------------------------------------------

CREATE TABLE app_user (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id      uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  issuer         text NOT NULL,
  subject        text NOT NULL,
  email          text NOT NULL,
  name           text NOT NULL,
  department     text,
  company_id     uuid,
  created_at     timestamptz NOT NULL DEFAULT now(),
  last_login_at  timestamptz,
  UNIQUE (tenant_id, id),
  UNIQUE (issuer, subject),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE SET NULL (company_id)
);
CREATE UNIQUE INDEX app_user_email_unique_per_tenant ON app_user (tenant_id, lower(email));
COMMENT ON TABLE app_user IS 'The native user directory, provisioned on first OIDC sign-in into the tenant that owns the token issuer; the identity provider never decides what a user may do.';

CREATE TABLE user_group (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  name         text NOT NULL,
  description  text NOT NULL DEFAULT '',
  valid_until  timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, name)
);
COMMENT ON TABLE user_group IS 'An Ontaix-native group; roles reach a user only through group membership.';

CREATE TABLE group_member (
  tenant_id  uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  group_id   uuid NOT NULL,
  user_id    uuid NOT NULL,
  added_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (group_id, user_id),
  FOREIGN KEY (tenant_id, group_id) REFERENCES user_group(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, user_id) REFERENCES app_user(tenant_id, id) ON DELETE CASCADE
);
COMMENT ON TABLE group_member IS 'Membership of a user in a group of the same tenant.';

CREATE TABLE group_role (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  group_id          uuid NOT NULL,
  role              role_name NOT NULL,
  scope_kind        scope_kind NOT NULL,
  scope_company_id  uuid,
  scope_domain_key  text REFERENCES domain_template(key),
  created_at        timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (tenant_id, group_id) REFERENCES user_group(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, scope_company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT group_role_scope_shape CHECK (
    (scope_kind = 'tenant'  AND scope_company_id IS NULL     AND scope_domain_key IS NULL) OR
    (scope_kind = 'company' AND scope_company_id IS NOT NULL AND scope_domain_key IS NULL) OR
    (scope_kind = 'domain'  AND scope_company_id IS NULL     AND scope_domain_key IS NOT NULL)
  ),
  CONSTRAINT group_role_administrator_tenant_only CHECK (role <> 'administrator' OR scope_kind = 'tenant'),
  CONSTRAINT group_role_agent_not_assignable CHECK (role <> 'agent')
);
CREATE UNIQUE INDEX group_role_unique ON group_role (
  group_id, role, scope_kind,
  coalesce(scope_company_id, '00000000-0000-0000-0000-000000000000'::uuid),
  coalesce(scope_domain_key, '')
);
COMMENT ON TABLE group_role IS 'A role held by a group on one scope: the tenant, one company, or one domain product family (a template key, covering that domain product in every company); duplicates are refused.';

CREATE TABLE agent (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  name         text NOT NULL,
  platform     text NOT NULL,
  issuer       text NOT NULL,
  subject      text NOT NULL,
  company_id   uuid,
  domain_key   text REFERENCES domain_template(key),
  owner_text   text NOT NULL DEFAULT '',
  access       boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, name),
  UNIQUE (issuer, subject),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE SET NULL (company_id)
);
CREATE INDEX agent_by_platform ON agent (tenant_id, platform);
COMMENT ON TABLE agent IS 'A machine identity from any platform: its token (issuer, subject) maps to this row; company_id null means tenant-wide scope; access can be switched off.';

CREATE TABLE agent_month_usage (
  tenant_id  uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  agent_id   uuid NOT NULL,
  month      date NOT NULL CHECK (month = date_trunc('month', month)::date),
  reads      bigint NOT NULL DEFAULT 0 CHECK (reads >= 0),
  cost_eur   numeric(12,2) NOT NULL DEFAULT 0 CHECK (cost_eur >= 0),
  PRIMARY KEY (agent_id, month),
  FOREIGN KEY (tenant_id, agent_id) REFERENCES agent(tenant_id, id) ON DELETE CASCADE
);
COMMENT ON TABLE agent_month_usage IS 'Measured model reads and cost in euros per agent per calendar month.';

CREATE TABLE cost_allocation (
  tenant_id      uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  month          date NOT NULL CHECK (month = date_trunc('month', month)::date),
  allocated_eur  numeric(12,2) NOT NULL CHECK (allocated_eur >= 0),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, month)
);
COMMENT ON TABLE cost_allocation IS 'The euro amount allocated to agent reads for a tenant and month, shown against the measured cost.';

CREATE TABLE llm_call (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id      uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  occurred_at    timestamptz NOT NULL DEFAULT now(),
  actor_kind     actor_kind NOT NULL CHECK (actor_kind IN ('user', 'agent')),
  actor_id       uuid NOT NULL,
  company_id     uuid,
  purpose        text NOT NULL CHECK (purpose IN ('teach_extraction')),
  provider       text NOT NULL CHECK (provider ~ '^[a-z0-9][a-z0-9_.-]{0,59}$'),
  model          text NOT NULL CHECK (char_length(model) BETWEEN 1 AND 120 AND model ~ '^[A-Za-z0-9][A-Za-z0-9_.:/@-]*$'),
  input_tokens   integer NOT NULL CHECK (input_tokens >= 0),
  output_tokens  integer NOT NULL CHECK (output_tokens >= 0),
  cost_eur       numeric(12,6) NOT NULL CHECK (cost_eur >= 0),
  latency_ms     integer NOT NULL CHECK (latency_ms BETWEEN 0 AND 60000),
  outcome        text NOT NULL CHECK (outcome IN ('used', 'invalid_output', 'timeout', 'provider_error')),
  UNIQUE (tenant_id, id)
);
CREATE INDEX llm_call_by_month ON llm_call (tenant_id, occurred_at);
CREATE INDEX llm_call_by_occurred ON llm_call (occurred_at);
COMMENT ON TABLE llm_call IS 'One cost record per call Ontaix makes to a language model provider, including failed and timed-out calls: who caused it (actor_id and company_id are plain uuids so the record survives the actor or company), why (purpose), which provider and model, token counts, the estimated euro cost from the deployment price table, latency and outcome. It never holds the sentence, the prompt, the answer or any credential. Cost management sums it per month; a purge deletes rows older than 400 days across all tenants through llm_call_by_occurred. It is inserted in its own short transaction after the call, never inside the request transaction.';

CREATE TABLE llm_month_usage (
  tenant_id  uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  month      date NOT NULL CHECK (month = date_trunc('month', month)::date),
  tokens     bigint NOT NULL DEFAULT 0 CHECK (tokens >= 0),
  PRIMARY KEY (tenant_id, month)
);
COMMENT ON TABLE llm_month_usage IS 'Tokens counted against tenant_settings.llm_monthly_token_cap per calendar month (UTC). Before a call the API reserves its upper bound (estimated input plus the maximum output tokens) with INSERT ... SELECT $reserve WHERE $reserve <= $cap ON CONFLICT (tenant_id, month) DO UPDATE SET tokens = llm_month_usage.tokens + EXCLUDED.tokens WHERE llm_month_usage.tokens + EXCLUDED.tokens <= $cap RETURNING tokens; zero rows returned means the cap is reached and the model step is skipped. The reservation commits in its own short transaction before the provider is called, never inside the request transaction, so no row lock is held during the call. After the call, in another short transaction, it settles with UPDATE ... SET tokens = greatest(tokens + $actual - $reserved, 0) WHERE tenant_id = $tenant AND month = $reserved_month, always the month the reservation was made in, even when the call ends in the next month. A call that times out or fails settles its actual count (0 when the provider reports none), which releases the rest of the reservation. A reservation whose process dies before settling stays counted until the month ends. Shared by every API replica.';

CREATE TABLE rate_budget_window (
  tenant_id     uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  actor_kind    actor_kind NOT NULL CHECK (actor_kind IN ('user', 'agent')),
  actor_id      uuid NOT NULL,
  budget        text NOT NULL CHECK (budget IN ('import', 'parse', 'proposal', 'llm')),
  window_start  timestamptz NOT NULL CHECK (extract(epoch FROM window_start) = floor(extract(epoch FROM window_start) / 3600) * 3600),
  spent         integer NOT NULL CHECK (spent >= 0),
  PRIMARY KEY (tenant_id, actor_kind, actor_id, budget, window_start)
);
CREATE INDEX rate_budget_window_by_start ON rate_budget_window (window_start);
COMMENT ON TABLE rate_budget_window IS 'Units spent per user or agent, per budget, per clock hour (window_start is a whole UTC hour), shared by every API replica. A charge of $n against $limit is one statement: INSERT INTO rate_budget_window (tenant_id, actor_kind, actor_id, budget, window_start, spent) SELECT $tenant, $kind, $actor, $budget, $window, $n WHERE $n <= $limit ON CONFLICT (tenant_id, actor_kind, actor_id, budget, window_start) DO UPDATE SET spent = rate_budget_window.spent + EXCLUDED.spent WHERE rate_budget_window.spent + EXCLUDED.spent <= $limit RETURNING spent; zero rows returned means the budget is exhausted and the call is refused (429 rate_limited, or llmOutcome rate_limited for the llm budget). actor_id is a plain uuid so a charge never waits on a foreign key lock. A purge every 15 minutes deletes windows that started more than 2 hours ago.';

-- ---------------------------------------------------------------------------
-- Proposals and approvals
-- ---------------------------------------------------------------------------

CREATE TABLE document_import (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  actor_kind       actor_kind NOT NULL,
  actor_user_id    uuid,
  actor_agent_id   uuid,
  file_name        text NOT NULL,
  media_type       text NOT NULL,
  sha256           bytea NOT NULL,
  sentence_count   integer NOT NULL,
  extracted_chars  integer NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  expires_at       timestamptz NOT NULL DEFAULT now() + interval '1 hour',
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, actor_user_id) REFERENCES app_user(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, actor_agent_id) REFERENCES agent(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT document_import_actor_matches_kind CHECK (
    (actor_kind = 'user'  AND actor_user_id IS NOT NULL AND actor_agent_id IS NULL) OR
    (actor_kind = 'agent' AND actor_agent_id IS NOT NULL AND actor_user_id IS NULL)
  ),
  CONSTRAINT document_import_file_name CHECK (
    char_length(file_name) BETWEEN 1 AND 255
    AND octet_length(file_name) <= 1020
    AND file_name !~ '[/\\:\x01-\x1f\x7f-\x9f\u200b-\u200f\u2028\u2029\u202a-\u202e\u061c\u2066-\u2069\ufeff]'
  ),
  CONSTRAINT document_import_media_type CHECK (media_type IN (
    'text/plain', 'text/markdown', 'text/csv', 'application/json',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf')),
  CONSTRAINT document_import_sha256 CHECK (octet_length(sha256) = 32),
  CONSTRAINT document_import_limits CHECK (sentence_count BETWEEN 0 AND 2000 AND extracted_chars BETWEEN 0 AND 2000000),
  CONSTRAINT document_import_one_hour CHECK (expires_at = created_at + interval '1 hour')
);
COMMENT ON TABLE document_import IS 'One uploaded document after server-side extraction: usable for one hour by the actor that created it, in its tenant. A purge every 15 minutes deletes imports whose expires_at is more than 24 hours old (their sentences cascade). Proposals copy the file name, media type, sentence index and position into proposal.origin_detail, so they survive the purge.';
CREATE INDEX document_import_by_expiry ON document_import (expires_at);

CREATE TABLE document_import_sentence (
  tenant_id       uuid NOT NULL,
  import_id       uuid NOT NULL,
  sentence_index  integer NOT NULL CHECK (sentence_index BETWEEN 0 AND 1999),
  text            text NOT NULL CHECK (char_length(text) BETWEEN 13 AND 399),
  position_unit   text CHECK (position_unit IN ('page', 'paragraph')),
  position_index  integer CHECK (position_index BETWEEN 1 AND 100000),
  parse_count     smallint NOT NULL DEFAULT 0 CHECK (parse_count BETWEEN 0 AND 3),
  drafted_at      timestamptz,
  PRIMARY KEY (tenant_id, import_id, sentence_index),
  FOREIGN KEY (tenant_id, import_id) REFERENCES document_import(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT document_import_sentence_position_pair CHECK ((position_unit IS NULL) = (position_index IS NULL))
);
COMMENT ON TABLE document_import_sentence IS 'Extracted sentences of an import in document order. parse_count caps teach parses per sentence at 3 and drafted_at marks the one proposal call allowed to cite the sentence; both are claimed with a conditional UPDATE ... RETURNING inside the calling transaction, and zero rows returned means the claim failed.';

CREATE TABLE teach_session_turn (
  tenant_id    uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  actor_kind   actor_kind NOT NULL CHECK (actor_kind IN ('user', 'agent')),
  actor_id     uuid NOT NULL,
  company_id   uuid NOT NULL,
  session_id   uuid NOT NULL,
  turn_index   integer NOT NULL CHECK (turn_index >= 0),
  sentence     text NOT NULL CHECK (char_length(sentence) BETWEEN 1 AND 400),
  extractor    text NOT NULL CHECK (extractor IN ('rules', 'llm', 'rules+llm')),
  concept_ids  uuid[] NOT NULL DEFAULT '{}',
  new_labels   text[] NOT NULL DEFAULT '{}',
  created_at   timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL DEFAULT now() + interval '2 hours',
  PRIMARY KEY (tenant_id, actor_kind, actor_id, company_id, session_id, turn_index),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT teach_session_turn_concept_ids CHECK (
    cardinality(concept_ids) <= 50 AND array_position(concept_ids, NULL) IS NULL
  ),
  CONSTRAINT teach_session_turn_new_labels CHECK (
    cardinality(new_labels) <= 50
    AND array_position(new_labels, NULL) IS NULL
    AND char_length(array_to_string(new_labels, '')) <= 6000
  ),
  CONSTRAINT teach_session_turn_two_hours CHECK (expires_at = created_at + interval '2 hours')
);
CREATE INDEX teach_session_turn_by_expiry ON teach_session_turn (expires_at);
COMMENT ON TABLE teach_session_turn IS 'The recent sentences of one teach bar session, so the teach extraction model step can resolve back-references. Keyed by tenant, caller (actor_kind, actor_id), company and the client-generated session_id; only that caller reads it. concept_ids are the existing concepts the sentence referenced (re-checked at read time: a stored id is used only if the concept still exists and would be a valid candidate now - taught company, or another company only while crossCompany is on and the caller may read it), new_labels the labels it introduced (resolved to ids at the next sentence when a proposal has created them). Turns are stored in one short transaction after the parse result is built: SELECT pg_advisory_xact_lock(hashtextextended(tenant_id || '':'' || actor_kind || '':'' || actor_id || '':'' || company_id || '':'' || session_id, 0)); INSERT ... SELECT coalesce(max(turn_index) + 1, 0) FROM teach_session_turn WHERE <session key>; DELETE the same session''s turns with turn_index <= n - 8. The advisory lock serialises concurrent sentences of one session, so turn numbers never collide and at most 8 turns are kept. If storing the turn fails anyway, the turn is not kept and the parse still answers 200; it is never an error. Reads ignore rows past expires_at (2 hours after each sentence); a purge every 15 minutes deletes them.';

CREATE TABLE proposal (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id          uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  type               proposal_type NOT NULL,
  change_kind        change_kind,
  state              proposal_state NOT NULL DEFAULT 'pending',
  title              text NOT NULL,
  color              text NOT NULL,
  company_id         uuid,
  domain_product_id  uuid,
  parent_label       text,
  deps               jsonb NOT NULL DEFAULT '[]'::jsonb,
  wait_for           text,
  html               text NOT NULL,
  why                text,
  caption            text,
  payload            jsonb NOT NULL DEFAULT '{}'::jsonb,
  concept_id         uuid,
  relation_id        uuid,
  relation_ids       uuid[] NOT NULL DEFAULT '{}',
  source_id          uuid,
  binding_ids        uuid[] NOT NULL DEFAULT '{}',
  attribute_id       uuid,
  proposer_kind      actor_kind NOT NULL,
  proposer_user_id   uuid,
  proposer_agent_id  uuid,
  bulk               boolean NOT NULL DEFAULT false,
  origin             proposal_origin NOT NULL DEFAULT 'text',
  origin_detail      jsonb,
  created_at         timestamptz NOT NULL DEFAULT now(),
  decided_at         timestamptz,
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, domain_product_id) REFERENCES domain_product(tenant_id, id) ON DELETE SET NULL (domain_product_id),
  FOREIGN KEY (tenant_id, concept_id) REFERENCES concept(tenant_id, id) ON DELETE SET NULL (concept_id),
  FOREIGN KEY (tenant_id, relation_id) REFERENCES relation(tenant_id, id) ON DELETE SET NULL (relation_id),
  FOREIGN KEY (tenant_id, source_id) REFERENCES source(tenant_id, id) ON DELETE SET NULL (source_id),
  FOREIGN KEY (tenant_id, attribute_id) REFERENCES attribute(tenant_id, id) ON DELETE SET NULL (attribute_id),
  FOREIGN KEY (tenant_id, proposer_user_id) REFERENCES app_user(tenant_id, id) ON DELETE SET NULL (proposer_user_id),
  FOREIGN KEY (tenant_id, proposer_agent_id) REFERENCES agent(tenant_id, id) ON DELETE SET NULL (proposer_agent_id),
  CONSTRAINT proposal_change_kind_only_for_change CHECK ((type = 'change') = (change_kind IS NOT NULL)),
  CONSTRAINT proposal_deps_is_array CHECK (jsonb_typeof(deps) = 'array'),
  CONSTRAINT proposal_origin_detail_iff_document CHECK ((origin = 'document') = (origin_detail IS NOT NULL)),
  CONSTRAINT proposal_origin_detail_shape CHECK (
    origin_detail IS NULL OR COALESCE((
      jsonb_typeof(origin_detail) = 'object'
      AND octet_length(origin_detail::text) <= 2048
      AND origin_detail ? 'fileName'
      AND origin_detail ? 'mediaType'
      AND origin_detail ? 'sentenceIndex'
      AND (origin_detail - 'fileName' - 'mediaType' - 'sentenceIndex' - 'position') = '{}'::jsonb
      AND jsonb_typeof(origin_detail -> 'fileName') = 'string'
      AND char_length(origin_detail ->> 'fileName') BETWEEN 1 AND 255
      AND octet_length(origin_detail ->> 'fileName') <= 1020
      AND (origin_detail ->> 'fileName') !~ '[/\\:\x01-\x1f\x7f-\x9f\u200b-\u200f\u2028\u2029\u202a-\u202e\u061c\u2066-\u2069\ufeff]'
      AND jsonb_typeof(origin_detail -> 'mediaType') = 'string'
      AND (origin_detail ->> 'mediaType') IN (
        'text/plain', 'text/markdown', 'text/csv', 'application/json',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf')
      AND jsonb_typeof(origin_detail -> 'sentenceIndex') = 'number'
      AND (origin_detail ->> 'sentenceIndex') ~ '^[0-9]{1,4}$'
      AND (origin_detail ->> 'sentenceIndex')::integer <= 1999
      AND (NOT (origin_detail ? 'position') OR (
        jsonb_typeof(origin_detail -> 'position') = 'object'
        AND ((origin_detail -> 'position') - 'unit' - 'index') = '{}'::jsonb
        AND (origin_detail -> 'position' ->> 'unit') IN ('page', 'paragraph')
        AND jsonb_typeof(origin_detail -> 'position' -> 'index') = 'number'
        AND (origin_detail -> 'position' ->> 'index') ~ '^[0-9]{1,6}$'
        AND (origin_detail -> 'position' ->> 'index')::integer BETWEEN 1 AND 100000
      ))
    ), false)
  ),
  CONSTRAINT proposal_decided_when_final CHECK ((state IN ('approved', 'rejected')) = (decided_at IS NOT NULL)),
  CONSTRAINT proposal_proposer_matches_kind CHECK (
    (proposer_kind = 'user'   AND proposer_user_id IS NOT NULL AND proposer_agent_id IS NULL) OR
    (proposer_kind = 'agent'  AND proposer_agent_id IS NOT NULL AND proposer_user_id IS NULL) OR
    (proposer_kind = 'system' AND proposer_user_id IS NULL AND proposer_agent_id IS NULL) OR
    (state IN ('approved', 'rejected'))
  )
);
CREATE INDEX proposal_open_by_tenant ON proposal (tenant_id, created_at) WHERE state IN ('pending', 'half_approved');
CREATE INDEX proposal_by_concept ON proposal (concept_id);
CREATE INDEX proposal_by_relation ON proposal (relation_id);
COMMENT ON TABLE proposal IS 'Every requested change to the ontology, with its pending artefacts, dependencies, panel texts and state; readiness is derived at read time and html holds server-escaped markup only.';

CREATE TABLE proposal_approval (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  proposal_id  uuid NOT NULL,
  ordinal      smallint NOT NULL CHECK (ordinal IN (1, 2)),
  user_id      uuid NOT NULL,
  approved_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (proposal_id, ordinal),
  UNIQUE (proposal_id, user_id),
  FOREIGN KEY (tenant_id, proposal_id) REFERENCES proposal(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, user_id) REFERENCES app_user(tenant_id, id) ON DELETE RESTRICT
);
COMMENT ON TABLE proposal_approval IS 'One row per approval of a proposal, always by a user; the second approver must be a different user, enforced by the unique pair.';

-- ---------------------------------------------------------------------------
-- Audit (append-only) and outbox
-- ---------------------------------------------------------------------------

CREATE TABLE audit_entry (
  id              bigserial PRIMARY KEY,
  tenant_id       uuid NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
  at              timestamptz NOT NULL DEFAULT now(),
  actor_kind      actor_kind NOT NULL,
  actor_user_id   uuid,
  actor_agent_id  uuid,
  kind            text NOT NULL,
  what            text NOT NULL,
  ok              boolean NOT NULL,
  proposal_id     uuid,
  origin          proposal_origin,
  company_ids     uuid[] NOT NULL DEFAULT '{}',
  domain_key      text REFERENCES domain_template(key),
  CHECK (array_position(company_ids, NULL) IS NULL),
  CONSTRAINT audit_entry_origin_only_for_proposal CHECK (origin IS NULL OR proposal_id IS NOT NULL)
);
CREATE INDEX audit_entry_by_tenant_time ON audit_entry (tenant_id, at DESC);
CREATE INDEX audit_entry_by_company_ids ON audit_entry USING gin (company_ids);
CREATE INDEX audit_entry_by_domain_key ON audit_entry (tenant_id, domain_key, at DESC) WHERE domain_key IS NOT NULL;
COMMENT ON TABLE audit_entry IS 'Append-only log of every approval, rejection, setting change and connection; actor and proposal ids are plain columns without foreign keys so deletions elsewhere never touch the log; update, delete and truncate are refused by trigger and the application role holds INSERT and SELECT only.';
COMMENT ON COLUMN audit_entry.company_ids IS 'Audience: every company whose name, labels or artefacts the entry mentions (both companies of a cross-company proposal, the added company of a company entry, the company of a role scope). Empty means tenant-wide. A reader sees the entry if it holds audit.read in a scope containing every listed company, or on the domain scope named by domain_key; an empty list needs audit.read at any scope. Checked against the tenant''s companies on insert; no foreign key, so a later company deletion never touches the log.';

CREATE FUNCTION audit_entry_is_append_only() RETURNS trigger
LANGUAGE plpgsql
SET search_path = ontaix, pg_catalog, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION 'audit_entry is append-only';
END;
$$;

CREATE TRIGGER audit_entry_no_update_or_delete
  BEFORE UPDATE OR DELETE ON audit_entry
  FOR EACH ROW EXECUTE FUNCTION audit_entry_is_append_only();

CREATE TRIGGER audit_entry_no_truncate
  BEFORE TRUNCATE ON audit_entry
  FOR EACH STATEMENT EXECUTE FUNCTION audit_entry_is_append_only();

CREATE TABLE outbox (
  id            bigserial PRIMARY KEY,
  tenant_id     uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  event_id      uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  aggregate     text NOT NULL,
  action        text NOT NULL,
  subject       text NOT NULL,
  visibility    text NOT NULL CHECK (visibility IN ('model.read', 'audit.read', 'group.manage', 'agent.manage')),
  company_ids   uuid[] NOT NULL DEFAULT '{}',
  domain_key    text REFERENCES domain_template(key),
  actor_kind    actor_kind NOT NULL,
  actor_id      uuid,
  bulk          boolean NOT NULL DEFAULT false,
  payload       jsonb NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  published_at  timestamptz,
  CHECK (array_position(company_ids, NULL) IS NULL),
  CONSTRAINT outbox_domain_key_only_for_audit CHECK (domain_key IS NULL OR visibility = 'audit.read')
);
CREATE INDEX outbox_unpublished ON outbox (id) WHERE published_at IS NULL;
CREATE INDEX outbox_by_tenant_sequence ON outbox (tenant_id, id);
COMMENT ON TABLE outbox IS 'Events written in the same transaction as the state change they describe, with the permission and the company audience that make each visible; the relay publishes them to NATS in id order.';
COMMENT ON COLUMN outbox.company_ids IS 'Audience: every company whose labels, names or artefact state the payload carries (bare ids do not count). Empty means tenant-wide. A subscriber receives the event only if it holds the visibility permission in a scope containing every listed company; an empty list needs the permission at any scope. Checked against the tenant''s companies on insert.';
COMMENT ON COLUMN outbox.domain_key IS 'Set only on audit.appended events, equal to the entry''s audit_entry.domain_key; a holder of audit.read on the domain scope with this key also receives the event.';

CREATE FUNCTION company_ids_belong_to_tenant() RETURNS trigger
LANGUAGE plpgsql
SET search_path = ontaix, pg_catalog, pg_temp
AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM unnest(NEW.company_ids) AS listed(id)
    WHERE NOT EXISTS (SELECT 1 FROM ontaix.company c WHERE c.tenant_id = NEW.tenant_id AND c.id = listed.id)
  ) THEN
    RAISE EXCEPTION '%.company_ids names a company outside tenant %', TG_TABLE_NAME, NEW.tenant_id;
  END IF;
  RETURN NEW;
END;
$$;
COMMENT ON COLUMN audit_entry.domain_key IS 'The template key of the domain product of the proposal the entry records, when that proposal has one; null for every other entry. A holder of audit.read on the domain scope with this key reads the entry whatever its company_ids, because that scope covers the domain product in every company and matches the proposals it may decide.';
COMMENT ON FUNCTION company_ids_belong_to_tenant() IS 'Composite tenant safety for company_ids arrays, which cannot carry a foreign key: every listed company must exist in the row''s tenant when the row is inserted. A removed company is marked dying before its row is deleted, so its removal events and audit entries still pass.';

CREATE TRIGGER outbox_company_ids_in_tenant
  BEFORE INSERT ON outbox
  FOR EACH ROW EXECUTE FUNCTION company_ids_belong_to_tenant();

CREATE TRIGGER audit_entry_company_ids_in_tenant
  BEFORE INSERT ON audit_entry
  FOR EACH ROW EXECUTE FUNCTION company_ids_belong_to_tenant();

CREATE TABLE projection_cursor (
  tenant_id       uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  company_id      uuid PRIMARY KEY,
  last_outbox_id  bigint NOT NULL,
  projected_at    timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE
);
COMMENT ON TABLE projection_cursor IS 'The last outbox id the Fuseki projector applied per company graph, so replayed events are skipped.';

-- ---------------------------------------------------------------------------
-- Reference data: domain templates and connector catalogue (contract constants)
-- ---------------------------------------------------------------------------

INSERT INTO domain_template (key, name, owner, color, position) VALUES
  ('production',  'Production',   'Plant operations',  '#3fb8a9', 0),
  ('supply',      'Supply chain', 'Procurement',       '#8b86cf', 1),
  ('sales',       'Sales',        'Commercial',        '#d9a15b', 2),
  ('logistics',   'Logistics',    'Distribution',      '#d98b6b', 3),
  ('quality',     'Quality',      'Quality assurance', '#cf7d98', 4),
  ('maintenance', 'Maintenance',  'Asset management',  '#7fb6d9', 5),
  ('finance',     'Finance',      'Controlling',       '#b9b36a', 6),
  ('people',      'People',       'Human resources',   '#8fbf7a', 7),
  ('engineering', 'Engineering',  'R&D',               '#c58ad0', 8);

INSERT INTO connector_type (code, name, category, scope_text, position) VALUES
  ('SAP',  'SAP ERP (S/4HANA, ECC)',    'ERP',           'OData / RFC · tables, CDS views',              0),
  ('SF',   'Salesforce',                'CRM',           'REST · objects and fields',                    1),
  ('D365', 'Microsoft Dynamics 365',    'ERP / CRM',     'Dataverse · tables',                           2),
  ('FAB',  'Microsoft Fabric · OneLake','data platform', 'Lakehouse, warehouse, Fabric IQ ontology',     3),
  ('DBX',  'Databricks',                'data platform', 'Unity Catalog · tables, Genie ontology',       4),
  ('SNW',  'Snowflake',                 'data platform', 'information schema · semantic views',          5),
  ('SQL',  'SQL Server · Azure SQL',    'database',      'schema and row counts',                        6),
  ('PG',   'PostgreSQL',                'database',      'schema and row counts',                        7),
  ('ORA',  'Oracle',                    'database',      'schema and row counts',                        8),
  ('MES',  'Siemens Opcenter · MES',    'MES',           'plants, lines, assets, orders',                9),
  ('X3',   'Sage X3',                   'ERP',           'facilities, items, business partners',         10),
  ('SN',   'ServiceNow',                'ITSM / CMMS',   'tables and CMDB',                              11),
  ('WD',   'Workday',                   'HRIS',          'workers, positions, organisations',            12),
  ('PI',   'AVEVA PI · OT',             'operations',    'tags and assets',                              13),
  ('SP',   'SharePoint · files',        'documents',     'glossaries, procedures, specifications',       14);

COMMIT;
