-- Ontaix control plane · PostgreSQL 16 schema.
-- System of record for the ontology, proposals, identity, bindings, audit and the outbox.
-- Every row belongs to one tenant: every table carries tenant_id, every parent exposes
-- UNIQUE (tenant_id, id), and every child foreign key is composite on (tenant_id, <parent>_id),
-- so a row can never reference another tenant's row. Identifiers are UUIDs generated by the database.
-- Domain product versions are integer revisions rendered as v1.<revision>.
-- Grants: the application role holds INSERT and SELECT only on audit_entry; nobody holds
-- UPDATE, DELETE or TRUNCATE on it, and the triggers below refuse them for every role.

BEGIN;

CREATE SCHEMA IF NOT EXISTS ontaix;
SET search_path TO ontaix, public;

-- ---------------------------------------------------------------------------
-- Enumerations
-- ---------------------------------------------------------------------------

CREATE TYPE node_kind AS ENUM ('root', 'concept');
CREATE TYPE relation_kind AS ENUM ('rel', 'isa', 'same', 'clash');
CREATE TYPE proposal_type AS ENUM ('concept', 'spec', 'relation', 'source', 'bind', 'attr', 'change');
CREATE TYPE proposal_state AS ENUM ('pending', 'half_approved', 'approved', 'rejected');
CREATE TYPE change_kind AS ENUM (
  'rename', 'delete_concept', 'edit_relation', 'remove_relation', 'unbind',
  'rename_source', 'remove_source', 'remove_company', 'resolve_conflict', 'remove_cross_company_links'
);
CREATE TYPE attribute_type AS ENUM ('id', 'text', 'number', 'ref', 'date');
CREATE TYPE attribute_state AS ENUM ('proposed', 'approved');
CREATE TYPE role_name AS ENUM ('owner', 'builder', 'governor', 'member', 'administrator', 'auditor', 'agent');
CREATE TYPE scope_kind AS ENUM ('tenant', 'company', 'domain');
CREATE TYPE actor_kind AS ENUM ('user', 'agent', 'system');
CREATE TYPE source_auth AS ENUM ('service_principal', 'oauth2_client_credentials', 'managed_identity', 'key_vault_api_key');
CREATE TYPE refresh_interval AS ENUM ('5 min', '15 min', '1 h', 'daily');
CREATE TYPE theme_name AS ENUM ('dark', 'light');
CREATE TYPE binding_freshness AS ENUM ('2 min', '4 min', '11 min', '1 h', 'paused', 'just now');

-- ---------------------------------------------------------------------------
-- Tenant, identity providers, settings, view state
-- ---------------------------------------------------------------------------

CREATE TABLE tenant (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        text NOT NULL UNIQUE,
  name        text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE tenant IS 'One customer of the control plane; every other row points at exactly one tenant.';

CREATE TABLE tenant_identity_provider (
  tenant_id   uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  issuer      text NOT NULL,
  audience    text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, issuer, audience),
  UNIQUE (issuer, audience)
);
COMMENT ON TABLE tenant_identity_provider IS 'Which OIDC issuer and audience pairs sign users and agents into which tenant; the pair is unique across tenants so a token maps to exactly one tenant.';

CREATE TABLE tenant_settings (
  tenant_id            uuid PRIMARY KEY REFERENCES tenant(id) ON DELETE CASCADE,
  theme                theme_name NOT NULL DEFAULT 'dark',
  colors               jsonb NOT NULL DEFAULT '{}'::jsonb,
  accent               text NOT NULL DEFAULT '#3fb8a9',
  source_colour        text NOT NULL DEFAULT '#d6bd8a',
  voice                boolean NOT NULL DEFAULT true,
  import_docs          boolean NOT NULL DEFAULT true,
  live_teaching        boolean NOT NULL DEFAULT true,
  everyone_teaches     boolean NOT NULL DEFAULT false,
  approval_required    boolean NOT NULL DEFAULT true CHECK (approval_required),
  two_approvers        boolean NOT NULL DEFAULT false,
  auto_attrs           boolean NOT NULL DEFAULT false,
  notify_owners        boolean NOT NULL DEFAULT true,
  multi_company        boolean NOT NULL DEFAULT true,
  cross_company        boolean NOT NULL DEFAULT true,
  animations           boolean NOT NULL DEFAULT true,
  coverage_default     boolean NOT NULL DEFAULT false,
  legend               boolean NOT NULL DEFAULT true,
  read_only_connectors boolean NOT NULL DEFAULT true CHECK (read_only_connectors),
  refresh              refresh_interval NOT NULL DEFAULT '15 min',
  agent_access         boolean NOT NULL DEFAULT true,
  cost_cap             boolean NOT NULL DEFAULT true,
  demo_story           boolean NOT NULL DEFAULT false,
  egress_allowlist     text[] NOT NULL DEFAULT '{}',
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tenant_settings_colors_is_object CHECK (jsonb_typeof(colors) = 'object')
);
COMMENT ON TABLE tenant_settings IS 'The 22 tenant settings plus appearance, the demo-story flag and the connector egress allowlist; the two locked settings are enforced by CHECK constraints.';

CREATE TABLE tenant_view_state (
  tenant_id   uuid PRIMARY KEY REFERENCES tenant(id) ON DELETE CASCADE,
  coverage    boolean NOT NULL DEFAULT false,
  scene_idx   integer NOT NULL DEFAULT 0 CHECK (scene_idx >= 0),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE tenant_view_state IS 'Shared canvas state that survives reload: the coverage flag and the demo scene index.';

-- ---------------------------------------------------------------------------
-- Ontology: companies, domain products, concepts, relations
-- ---------------------------------------------------------------------------

CREATE TABLE company (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  key         text NOT NULL,
  name        text NOT NULL,
  sub         text NOT NULL DEFAULT '',
  position    integer NOT NULL,
  is_home     boolean NOT NULL DEFAULT false,
  dying_at    timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, key),
  UNIQUE (tenant_id, position)
);
CREATE UNIQUE INDEX company_one_home_per_tenant ON company (tenant_id) WHERE is_home;
COMMENT ON TABLE company IS 'A business-as-a-product in the tenant; the home company (position 0) cannot be removed.';

CREATE TABLE domain_template (
  key         text PRIMARY KEY,
  name        text NOT NULL,
  owner       text NOT NULL,
  color       text NOT NULL,
  position    integer NOT NULL UNIQUE
);
COMMENT ON TABLE domain_template IS 'The nine fixed domain product templates every company is instantiated from, in ring order.';

CREATE TABLE domain_product (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  company_id    uuid NOT NULL,
  template_key  text NOT NULL REFERENCES domain_template(key),
  revision      integer NOT NULL DEFAULT 0 CHECK (revision >= 0),
  hidden        boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (company_id, template_key),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE
);
COMMENT ON TABLE domain_product IS 'One owned, versioned slice per company and template; revision increments by one on every approved change that carries the domain.';

CREATE TABLE concept (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id          uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  company_id         uuid NOT NULL,
  kind               node_kind NOT NULL DEFAULT 'concept',
  label              text NOT NULL,
  sub                text NOT NULL DEFAULT '',
  domain_product_id  uuid,
  rule               text,
  pending            boolean NOT NULL DEFAULT true,
  conflict           boolean NOT NULL DEFAULT false,
  parent_id          uuid,
  birth_relation_id  uuid,
  birth_action       text,
  birth_reverse      boolean NOT NULL DEFAULT false,
  born_at            timestamptz NOT NULL DEFAULT now(),
  x                  double precision NOT NULL DEFAULT 0,
  y                  double precision NOT NULL DEFAULT 0,
  pinned             boolean NOT NULL DEFAULT false,
  dying_at           timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, domain_product_id) REFERENCES domain_product(tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, parent_id) REFERENCES concept(tenant_id, id) ON DELETE SET NULL (parent_id),
  CONSTRAINT concept_root_has_no_domain CHECK (kind <> 'root' OR domain_product_id IS NULL),
  CONSTRAINT concept_root_has_no_parent CHECK (kind <> 'root' OR parent_id IS NULL),
  CONSTRAINT concept_non_root_has_domain CHECK (kind = 'root' OR domain_product_id IS NOT NULL),
  CONSTRAINT concept_non_root_has_birth_action CHECK (kind = 'root' OR birth_action IS NOT NULL),
  CONSTRAINT concept_label_not_blank CHECK (length(btrim(label)) > 0)
);
CREATE UNIQUE INDEX concept_one_root_per_company ON concept (company_id) WHERE kind = 'root';
CREATE UNIQUE INDEX concept_label_unique_per_company ON concept (company_id, lower(label)) WHERE dying_at IS NULL;
CREATE INDEX concept_by_domain ON concept (domain_product_id);
CREATE INDEX concept_by_parent ON concept (parent_id);
COMMENT ON TABLE concept IS 'A cell on the canvas: the company root or a concept born by division, with its lineage (parent, birth link, birth action and direction, born_at) and stored position.';

CREATE TABLE relation (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  a_id        uuid NOT NULL,
  b_id        uuid NOT NULL,
  kind        relation_kind NOT NULL,
  label       text NOT NULL,
  rest        numeric(6,1) NOT NULL,
  seed        double precision NOT NULL,
  pending     boolean NOT NULL DEFAULT true,
  dying_at    timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, a_id) REFERENCES concept(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, b_id) REFERENCES concept(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT relation_ends_differ CHECK (a_id <> b_id),
  CONSTRAINT relation_seed_unit CHECK (seed >= 0 AND seed < 1),
  CONSTRAINT relation_structural_label CHECK (
    (kind = 'isa' AND label = 'is a') OR
    (kind = 'same' AND label = 'equivalent to') OR
    (kind = 'clash' AND label = 'conflicts with') OR
    (kind = 'rel')
  )
);
CREATE UNIQUE INDEX relation_unique_triple ON relation (a_id, lower(label), b_id) WHERE dying_at IS NULL;
CREATE INDEX relation_by_a ON relation (a_id);
CREATE INDEX relation_by_b ON relation (b_id);
COMMENT ON TABLE relation IS 'A directed line between two concepts: action relation, specialisation (is a), cross-company equivalence or a noticed conflict.';

ALTER TABLE concept
  ADD CONSTRAINT concept_birth_relation_fk FOREIGN KEY (tenant_id, birth_relation_id)
  REFERENCES relation(tenant_id, id) ON DELETE SET NULL (birth_relation_id) DEFERRABLE INITIALLY DEFERRED;

-- ---------------------------------------------------------------------------
-- Bindings: connectors, sources, bindings, attributes
-- ---------------------------------------------------------------------------

CREATE TABLE connector_type (
  code        text PRIMARY KEY,
  name        text NOT NULL,
  category    text NOT NULL,
  scope_text  text NOT NULL,
  position    integer NOT NULL UNIQUE
);
COMMENT ON TABLE connector_type IS 'The read-only connector catalogue shown on the Connectors page and in wizard step 1.';

CREATE TABLE source (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  company_id      uuid NOT NULL,
  label           text NOT NULL,
  kind_text       text NOT NULL,
  connector_code  text REFERENCES connector_type(code),
  host            text,
  scope           text,
  auth            source_auth,
  credential_ref  text CHECK (credential_ref ~ '^[A-Za-z0-9-]{1,127}$'),
  refresh         refresh_interval NOT NULL DEFAULT '15 min',
  anchor_index    integer NOT NULL CHECK (anchor_index >= 0),
  disabled        boolean NOT NULL DEFAULT false,
  pending         boolean NOT NULL DEFAULT true,
  x               double precision NOT NULL DEFAULT 0,
  y               double precision NOT NULL DEFAULT 0,
  pinned          boolean NOT NULL DEFAULT false,
  dying_at        timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX source_label_unique_per_company ON source (company_id, lower(label)) WHERE dying_at IS NULL;
COMMENT ON TABLE source IS 'A connected system drawn as a brass square outside the domain ring; credential_ref is a Key Vault secret name, never a credential value.';

CREATE TABLE binding (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  source_id   uuid NOT NULL,
  concept_id  uuid NOT NULL,
  records     bigint NOT NULL DEFAULT 0 CHECK (records >= 0),
  fresh       binding_freshness NOT NULL DEFAULT '2 min',
  pending     boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (concept_id),
  FOREIGN KEY (tenant_id, source_id) REFERENCES source(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, concept_id) REFERENCES concept(tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX binding_by_source ON binding (source_id);
COMMENT ON TABLE binding IS 'The bind link from a source to a concept with record count and freshness; a concept has at most one binding.';

CREATE TABLE attribute (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  concept_id  uuid NOT NULL,
  source_id   uuid,
  name        text NOT NULL,
  type        attribute_type NOT NULL,
  col         text NOT NULL,
  fill        smallint NOT NULL CHECK (fill BETWEEN 0 AND 100),
  state       attribute_state NOT NULL DEFAULT 'proposed',
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (concept_id, name),
  FOREIGN KEY (tenant_id, concept_id) REFERENCES concept(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, source_id) REFERENCES source(tenant_id, id) ON DELETE SET NULL (source_id)
);
COMMENT ON TABLE attribute IS 'An attribute read from a bound source: name, type, source column, fill percentage and whether it is approved or still proposed.';

-- ---------------------------------------------------------------------------
-- Identity: users, groups, roles, agents, cost
-- ---------------------------------------------------------------------------

CREATE TABLE app_user (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id      uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  issuer         text NOT NULL,
  subject        text NOT NULL,
  email          text NOT NULL,
  name           text NOT NULL,
  department     text,
  company_id     uuid,
  created_at     timestamptz NOT NULL DEFAULT now(),
  last_login_at  timestamptz,
  UNIQUE (tenant_id, id),
  UNIQUE (issuer, subject),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE SET NULL (company_id)
);
CREATE UNIQUE INDEX app_user_email_unique_per_tenant ON app_user (tenant_id, lower(email));
COMMENT ON TABLE app_user IS 'The native user directory, provisioned on first OIDC sign-in into the tenant that owns the token issuer; the identity provider never decides what a user may do.';

CREATE TABLE user_group (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  name         text NOT NULL,
  description  text NOT NULL DEFAULT '',
  valid_until  timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, name)
);
COMMENT ON TABLE user_group IS 'An Ontaix-native group; roles reach a user only through group membership.';

CREATE TABLE group_member (
  tenant_id  uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  group_id   uuid NOT NULL,
  user_id    uuid NOT NULL,
  added_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (group_id, user_id),
  FOREIGN KEY (tenant_id, group_id) REFERENCES user_group(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, user_id) REFERENCES app_user(tenant_id, id) ON DELETE CASCADE
);
COMMENT ON TABLE group_member IS 'Membership of a user in a group of the same tenant.';

CREATE TABLE group_role (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  group_id          uuid NOT NULL,
  role              role_name NOT NULL,
  scope_kind        scope_kind NOT NULL,
  scope_company_id  uuid,
  scope_domain_key  text REFERENCES domain_template(key),
  created_at        timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (tenant_id, group_id) REFERENCES user_group(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, scope_company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT group_role_scope_shape CHECK (
    (scope_kind = 'tenant'  AND scope_company_id IS NULL     AND scope_domain_key IS NULL) OR
    (scope_kind = 'company' AND scope_company_id IS NOT NULL AND scope_domain_key IS NULL) OR
    (scope_kind = 'domain'  AND scope_company_id IS NULL     AND scope_domain_key IS NOT NULL)
  ),
  CONSTRAINT group_role_administrator_tenant_only CHECK (role <> 'administrator' OR scope_kind = 'tenant'),
  CONSTRAINT group_role_agent_not_assignable CHECK (role <> 'agent')
);
CREATE UNIQUE INDEX group_role_unique ON group_role (
  group_id, role, scope_kind,
  coalesce(scope_company_id, '00000000-0000-0000-0000-000000000000'::uuid),
  coalesce(scope_domain_key, '')
);
COMMENT ON TABLE group_role IS 'A role held by a group on one scope: the tenant, one company, or one domain product family (a template key, covering that domain product in every company); duplicates are refused.';

CREATE TABLE agent (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  name         text NOT NULL,
  platform     text NOT NULL,
  issuer       text NOT NULL,
  subject      text NOT NULL,
  company_id   uuid,
  domain_key   text REFERENCES domain_template(key),
  owner_text   text NOT NULL DEFAULT '',
  access       boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, name),
  UNIQUE (issuer, subject),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE SET NULL (company_id)
);
CREATE INDEX agent_by_platform ON agent (tenant_id, platform);
COMMENT ON TABLE agent IS 'A machine identity from any platform: its token (issuer, subject) maps to this row; company_id null means tenant-wide scope; access can be switched off.';

CREATE TABLE agent_month_usage (
  tenant_id  uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  agent_id   uuid NOT NULL,
  month      date NOT NULL CHECK (month = date_trunc('month', month)::date),
  reads      bigint NOT NULL DEFAULT 0 CHECK (reads >= 0),
  cost_eur   numeric(12,2) NOT NULL DEFAULT 0 CHECK (cost_eur >= 0),
  PRIMARY KEY (agent_id, month),
  FOREIGN KEY (tenant_id, agent_id) REFERENCES agent(tenant_id, id) ON DELETE CASCADE
);
COMMENT ON TABLE agent_month_usage IS 'Measured model reads and cost in euros per agent per calendar month.';

CREATE TABLE cost_allocation (
  tenant_id      uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  month          date NOT NULL CHECK (month = date_trunc('month', month)::date),
  allocated_eur  numeric(12,2) NOT NULL CHECK (allocated_eur >= 0),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, month)
);
COMMENT ON TABLE cost_allocation IS 'The euro amount allocated to agent reads for a tenant and month, shown against the measured cost.';

-- ---------------------------------------------------------------------------
-- Proposals and approvals
-- ---------------------------------------------------------------------------

CREATE TABLE proposal (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id          uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  type               proposal_type NOT NULL,
  change_kind        change_kind,
  state              proposal_state NOT NULL DEFAULT 'pending',
  title              text NOT NULL,
  color              text NOT NULL,
  company_id         uuid,
  domain_product_id  uuid,
  parent_label       text,
  deps               jsonb NOT NULL DEFAULT '[]'::jsonb,
  wait_for           text,
  html               text NOT NULL,
  why                text,
  caption            text,
  payload            jsonb NOT NULL DEFAULT '{}'::jsonb,
  concept_id         uuid,
  relation_id        uuid,
  relation_ids       uuid[] NOT NULL DEFAULT '{}',
  source_id          uuid,
  binding_ids        uuid[] NOT NULL DEFAULT '{}',
  attribute_id       uuid,
  proposer_kind      actor_kind NOT NULL,
  proposer_user_id   uuid,
  proposer_agent_id  uuid,
  bulk               boolean NOT NULL DEFAULT false,
  created_at         timestamptz NOT NULL DEFAULT now(),
  decided_at         timestamptz,
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, domain_product_id) REFERENCES domain_product(tenant_id, id) ON DELETE SET NULL (domain_product_id),
  FOREIGN KEY (tenant_id, concept_id) REFERENCES concept(tenant_id, id) ON DELETE SET NULL (concept_id),
  FOREIGN KEY (tenant_id, relation_id) REFERENCES relation(tenant_id, id) ON DELETE SET NULL (relation_id),
  FOREIGN KEY (tenant_id, source_id) REFERENCES source(tenant_id, id) ON DELETE SET NULL (source_id),
  FOREIGN KEY (tenant_id, attribute_id) REFERENCES attribute(tenant_id, id) ON DELETE SET NULL (attribute_id),
  FOREIGN KEY (tenant_id, proposer_user_id) REFERENCES app_user(tenant_id, id) ON DELETE SET NULL (proposer_user_id),
  FOREIGN KEY (tenant_id, proposer_agent_id) REFERENCES agent(tenant_id, id) ON DELETE SET NULL (proposer_agent_id),
  CONSTRAINT proposal_change_kind_only_for_change CHECK ((type = 'change') = (change_kind IS NOT NULL)),
  CONSTRAINT proposal_deps_is_array CHECK (jsonb_typeof(deps) = 'array'),
  CONSTRAINT proposal_decided_when_final CHECK ((state IN ('approved', 'rejected')) = (decided_at IS NOT NULL)),
  CONSTRAINT proposal_proposer_matches_kind CHECK (
    (proposer_kind = 'user'   AND proposer_user_id IS NOT NULL AND proposer_agent_id IS NULL) OR
    (proposer_kind = 'agent'  AND proposer_agent_id IS NOT NULL AND proposer_user_id IS NULL) OR
    (proposer_kind = 'system' AND proposer_user_id IS NULL AND proposer_agent_id IS NULL) OR
    (state IN ('approved', 'rejected'))
  )
);
CREATE INDEX proposal_open_by_tenant ON proposal (tenant_id, created_at) WHERE state IN ('pending', 'half_approved');
CREATE INDEX proposal_by_concept ON proposal (concept_id);
CREATE INDEX proposal_by_relation ON proposal (relation_id);
COMMENT ON TABLE proposal IS 'Every requested change to the ontology, with its pending artefacts, dependencies, panel texts and state; readiness is derived at read time and html holds server-escaped markup only.';

CREATE TABLE proposal_approval (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  proposal_id  uuid NOT NULL,
  ordinal      smallint NOT NULL CHECK (ordinal IN (1, 2)),
  user_id      uuid NOT NULL,
  approved_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (proposal_id, ordinal),
  UNIQUE (proposal_id, user_id),
  FOREIGN KEY (tenant_id, proposal_id) REFERENCES proposal(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, user_id) REFERENCES app_user(tenant_id, id) ON DELETE RESTRICT
);
COMMENT ON TABLE proposal_approval IS 'One row per approval of a proposal, always by a user; the second approver must be a different user, enforced by the unique pair.';

-- ---------------------------------------------------------------------------
-- Audit (append-only) and outbox
-- ---------------------------------------------------------------------------

CREATE TABLE audit_entry (
  id              bigserial PRIMARY KEY,
  tenant_id       uuid NOT NULL REFERENCES tenant(id) ON DELETE RESTRICT,
  at              timestamptz NOT NULL DEFAULT now(),
  actor_kind      actor_kind NOT NULL,
  actor_user_id   uuid,
  actor_agent_id  uuid,
  kind            text NOT NULL,
  what            text NOT NULL,
  ok              boolean NOT NULL,
  proposal_id     uuid
);
CREATE INDEX audit_entry_by_tenant_time ON audit_entry (tenant_id, at DESC);
COMMENT ON TABLE audit_entry IS 'Append-only log of every approval, rejection, setting change and connection; actor and proposal ids are plain columns without foreign keys so deletions elsewhere never touch the log; update, delete and truncate are refused by trigger and the application role holds INSERT and SELECT only.';

CREATE FUNCTION audit_entry_is_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit_entry is append-only';
END;
$$;

CREATE TRIGGER audit_entry_no_update_or_delete
  BEFORE UPDATE OR DELETE ON audit_entry
  FOR EACH ROW EXECUTE FUNCTION audit_entry_is_append_only();

CREATE TRIGGER audit_entry_no_truncate
  BEFORE TRUNCATE ON audit_entry
  FOR EACH STATEMENT EXECUTE FUNCTION audit_entry_is_append_only();

CREATE TABLE outbox (
  id            bigserial PRIMARY KEY,
  tenant_id     uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  event_id      uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  aggregate     text NOT NULL,
  action        text NOT NULL,
  subject       text NOT NULL,
  visibility    text NOT NULL CHECK (visibility IN ('model.read', 'audit.read', 'group.manage', 'agent.manage')),
  company_id    uuid,
  actor_kind    actor_kind NOT NULL,
  actor_id      uuid,
  bulk          boolean NOT NULL DEFAULT false,
  payload       jsonb NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  published_at  timestamptz,
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE SET NULL (company_id)
);
CREATE INDEX outbox_unpublished ON outbox (id) WHERE published_at IS NULL;
CREATE INDEX outbox_by_tenant_sequence ON outbox (tenant_id, id);
COMMENT ON TABLE outbox IS 'Events written in the same transaction as the state change they describe, with the permission that makes each visible; the relay publishes them to NATS in id order.';

CREATE TABLE projection_cursor (
  tenant_id       uuid NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
  company_id      uuid PRIMARY KEY,
  last_outbox_id  bigint NOT NULL,
  projected_at    timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (tenant_id, company_id) REFERENCES company(tenant_id, id) ON DELETE CASCADE
);
COMMENT ON TABLE projection_cursor IS 'The last outbox id the Fuseki projector applied per company graph, so replayed events are skipped.';

-- ---------------------------------------------------------------------------
-- Reference data: domain templates and connector catalogue (contract constants)
-- ---------------------------------------------------------------------------

INSERT INTO domain_template (key, name, owner, color, position) VALUES
  ('production',  'Production',   'Plant operations',  '#3fb8a9', 0),
  ('supply',      'Supply chain', 'Procurement',       '#8b86cf', 1),
  ('sales',       'Sales',        'Commercial',        '#d9a15b', 2),
  ('logistics',   'Logistics',    'Distribution',      '#d98b6b', 3),
  ('quality',     'Quality',      'Quality assurance', '#cf7d98', 4),
  ('maintenance', 'Maintenance',  'Asset management',  '#7fb6d9', 5),
  ('finance',     'Finance',      'Controlling',       '#b9b36a', 6),
  ('people',      'People',       'Human resources',   '#8fbf7a', 7),
  ('engineering', 'Engineering',  'R&D',               '#c58ad0', 8);

INSERT INTO connector_type (code, name, category, scope_text, position) VALUES
  ('SAP',  'SAP ERP (S/4HANA, ECC)',    'ERP',           'OData / RFC · tables, CDS views',              0),
  ('SF',   'Salesforce',                'CRM',           'REST · objects and fields',                    1),
  ('D365', 'Microsoft Dynamics 365',    'ERP / CRM',     'Dataverse · tables',                           2),
  ('FAB',  'Microsoft Fabric · OneLake','data platform', 'Lakehouse, warehouse, Fabric IQ ontology',     3),
  ('DBX',  'Databricks',                'data platform', 'Unity Catalog · tables, Genie ontology',       4),
  ('SNW',  'Snowflake',                 'data platform', 'information schema · semantic views',          5),
  ('SQL',  'SQL Server · Azure SQL',    'database',      'schema and row counts',                        6),
  ('PG',   'PostgreSQL',                'database',      'schema and row counts',                        7),
  ('ORA',  'Oracle',                    'database',      'schema and row counts',                        8),
  ('MES',  'Siemens Opcenter · MES',    'MES',           'plants, lines, assets, orders',                9),
  ('X3',   'Sage X3',                   'ERP',           'facilities, items, business partners',         10),
  ('SN',   'ServiceNow',                'ITSM / CMMS',   'tables and CMDB',                              11),
  ('WD',   'Workday',                   'HRIS',          'workers, positions, organisations',            12),
  ('PI',   'AVEVA PI · OT',             'operations',    'tags and assets',                              13),
  ('SP',   'SharePoint · files',        'documents',     'glossaries, procedures, specifications',       14);

COMMIT;
